# Generated by Django 5.2.5 on 2025-08-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('symptoms', models.TextField()),
                ('nurse_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Paitent_booking',
        ),
    ]
