# Generated by Django 5.2.5 on 2025-08-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_patientprofile_delete_patientbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='service_type',
            field=models.CharField(choices=[('general', 'General Visit'), ('Surgery', 'Post Surgery'), ('Elderly', 'Elderly Care'), ('Pedo', 'Pediatric Care'), ('pregnancy', 'Post Pregnancy Care')], max_length=20),
        ),
    ]
