# Generated by Django 5.2.5 on 2025-08-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
