# Generated by Django 5.2.5 on 2025-08-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('Pin_code', models.CharField(max_length=10)),
                ('experience', models.IntegerField()),
                ('specialization', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('varified', models.BooleanField(default=False)),
            ],
        ),
    ]
