# Generated by Django 5.2.5 on 2025-08-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nurse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse_info',
            name='city',
        ),
    ]
